### ISSUE TITLE
"Could not create directory '/.ssh'."

### ISSUE THREAD

**Issue by Leonetienne** [SemanticComputing/docker-rsync#1]
Hellow,
I am trying to use this image in a drone cicd pipeline to deploy to my server, but the image errors out with the message above.

Here's the full output of the step:
```
default
rsync ${RSYNC_OPTIONS:-} ${SSH_COMMAND:+-e "$SSH_COMMAND"} "$RSYNC_SOURCE" "$RSYNC_TARGET"
Could not create directory '/.ssh'.
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.3]
```

and here's my env-variable setup:
```
  - name: Deploy doxygen reference
    image: secoresearch/rsync
    environment:
      SSH_PRIVATE_KEY:
        from_secret: ssh-priv
      SSH_KNOWN_HOSTS:
        from_secret: known-hosts
      RSYNC_SOURCE: ./reference/build/html/
      RSYNC_TARGET: <user>@<server>:reference
      SSH_COMMAND: "ssh -o IdentitiesOnly=yes -p <non-22 port>"
      RSYNC_OPTIONS: >-
          -avz
          --recursive
          --delete
          --delete-excluded
```

Any ideas? I really like this env-variable only idea. The private key, and the known-hosts did work with other rsync setups.
Same happens with existing ssh files.
